spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/Book
    username: postgres
    password: admin#123
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.jdbc.lob.non_contextual_creation: true

